import json
import os

curriculum_file = "/home/ubuntu/Shine_Academy_Naroda/app_core/curriculum/gseb_class9.json"
chapters_dir = "/home/ubuntu/Shine_Academy_Naroda/app_core/chapters/"
assessment_dir = "/home/ubuntu/Shine_Academy_Naroda/app_core/assessment/"

os.makedirs(chapters_dir, exist_ok=True)
os.makedirs(assessment_dir, exist_ok=True)

syllabus = {
    "gseb_class9_maths": {
        "name": "Mathematics",
        "chapters": [
            "Chapter 1: Number Systems",
            "Chapter 2: Polynomials",
            "Chapter 3: Coordinate Geometry",
            "Chapter 4: Linear Equations in Two Variables",
            "Chapter 5: Introduction to Euclid's Geometry"
        ]
    },
    "gseb_class9_social": {
        "name": "Social Science",
        "chapters": [
            "Chapter 1: Rise of British Rule in India",
            "Chapter 2: First World War and Russian Revolution",
            "Chapter 3: Movement towards a New World",
            "Chapter 4: National Movements in India",
            "Chapter 5: Movement towards Independence"
        ]
    },
    "gseb_class9_english": {
        "name": "English",
        "chapters": [
            "Chapter 1: Cheetah's Tears",
            "Chapter 2: Dental Health",
            "Chapter 3: Mohan And His Veena",
            "Chapter 4: Call Of The Hills",
            "Chapter 5: Rani Ki Vaav"
        ]
    }
}

with open(curriculum_file, 'r', encoding='utf-8') as f:
    curriculum = json.load(f)

for subject_id, subject_data in syllabus.items():
    subject_entry = next((s for s in curriculum['subjects'] if s['id'] == subject_id), None)
    
    if not subject_entry:
        subject_entry = {
            "id": subject_id,
            "name": subject_data["name"],
            "chapters": []
        }
        curriculum['subjects'].append(subject_entry)
        
    for i, ch_title in enumerate(subject_data["chapters"], 1):
        ch_id = f"{subject_id}_ch{i}"
        
        # Add to curriculum if not exists
        if not any(c['chapter_id'] == ch_id for c in subject_entry['chapters']):
            subject_entry['chapters'].append({
                "chapter_id": ch_id,
                "title": ch_title,
                "module_id": ch_id
            })
            
        # Generate chapter JSON file
        ch_filepath = os.path.join(chapters_dir, f"{ch_id}.json")
        if not os.path.exists(ch_filepath):
            ch_content = {
                "metadata": {
                    "title": ch_title.split(": ")[1] if ": " in ch_title else ch_title,
                    "subject": subject_data["name"],
                    "grade": "9",
                    "curriculum": ["GSEB"],
                    "difficulty": "Intermediate",
                    "version": "1.0.0",
                    "id": ch_id
                },
                "blocks": [
                    {
                        "type": "theory",
                        "content": f"Welcome to {ch_title}. This is an introductory module generated by the EduOS Swarm."
                    },
                    {
                        "type": "teacher_tip",
                        "content": "Remember to connect this concept to real life examples."
                    }
                ]
            }
            with open(ch_filepath, 'w', encoding='utf-8') as f_ch:
                json.dump(ch_content, f_ch, indent=2)

with open(curriculum_file, 'w', encoding='utf-8') as f:
    json.dump(curriculum, f, indent=2)

print("Class 9 content generated successfully.")
